#!/usr/bin/env bash
# Regenerate the skills table in README.md between SKILLS:START and SKILLS:END markers.
# Idempotent. Exits 0 if README is already up to date, 0 if updated.

set -u

cd "$(dirname "$0")/.." || exit 2

README="README.md"
START_MARKER="<!-- SKILLS:START -->"
END_MARKER="<!-- SKILLS:END -->"

if [[ ! -f "$README" ]]; then
  echo "README.md not found" >&2
  exit 1
fi

if ! grep -qF "$START_MARKER" "$README" || ! grep -qF "$END_MARKER" "$README"; then
  echo "README.md missing $START_MARKER / $END_MARKER markers" >&2
  exit 1
fi

extract_field() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { fm++; next }
    fm == 1 {
      if (match($0, "^" key ":[[:space:]]*")) {
        print substr($0, RLENGTH+1)
        exit
      }
    }
  ' "$1"
}

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

unquote() {
  local s="$1"
  if [[ "$s" =~ ^\".*\"$ ]] || [[ "$s" =~ ^\'.*\'$ ]]; then
    s="${s:1:${#s}-2}"
  fi
  printf '%s' "$s"
}

# Build the new table block
{
  echo "$START_MARKER"
  echo "<!-- Auto-generated by scripts/generate-index.sh — do not edit between markers. -->"
  echo
  echo "| Skill | Version | Description |"
  echo "|---|---|---|"
  shopt -s nullglob
  for dir in skills/*/; do
    base="$(basename "$dir")"
    [[ "$base" == .* || "$base" == _* ]] && continue
    skill_md="${dir}SKILL.md"
    [[ -f "$skill_md" ]] || continue
    name="$(unquote "$(trim "$(extract_field "$skill_md" name)")")"
    version="$(unquote "$(trim "$(extract_field "$skill_md" version)")")"
    description="$(unquote "$(trim "$(extract_field "$skill_md" description)")")"
    [[ -z "$name" ]] && name="$base"
    [[ -z "$version" ]] && version="—"
    # Truncate description for the table
    if (( ${#description} > 160 )); then
      description="${description:0:157}..."
    fi
    # Escape pipe chars
    description="${description//|/\\|}"
    echo "| [$name](skills/$name/) | \`$version\` | $description |"
  done
  echo
  echo "$END_MARKER"
} > /tmp/skills-index.md

# Splice into README
awk -v start="$START_MARKER" -v end="$END_MARKER" -v block_file=/tmp/skills-index.md '
  BEGIN {
    while ((getline line < block_file) > 0) {
      block = block (block ? "\n" : "") line
    }
    close(block_file)
  }
  $0 ~ start { print block; in_block=1; next }
  $0 ~ end   { in_block=0; next }
  !in_block  { print }
' "$README" > /tmp/README.new

if cmp -s "$README" /tmp/README.new; then
  echo "README.md already up to date"
  rm -f /tmp/README.new /tmp/skills-index.md
  exit 0
fi

mv /tmp/README.new "$README"
rm -f /tmp/skills-index.md
echo "README.md updated"
exit 0
